### ISSUE TITLE
release 

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/fablab-ios#3]
- [x] Build number erhöhen wie https://github.com/fau-fablab/fablab-ios/commit/cd4d5fc8c33c1a4b229f14be6e625530d03c9a61
- [x] Mail an andreas

**Comment by andreaskumlehn** [comment]
- [x] update server certificate
- [x] fix server url

**Comment by sebhaub** [comment]
server cert / url --> see https://github.com/fau-fablab/fablab-ios/pull/1
